version: '3'

services:
  fuckzoom:
    build: .
    container_name: fuckzoom
    ports:
      - "8889:80"
    restart: always
    volumes:
      - /matrix/static-files/public/fuckzoom:/usr/share/nginx/html:ro